### ISSUE TITLE
Can not do arithmatic operations for decimal numbers. 

### ISSUE THREAD

**Issue by sujeewasandeepa** [Amaya-2001/JS-BasicCalculator#1]
Doesn't handle decimal numbers, 
![image](https://github.com/Amaya-2001/JS-BasicCalculator/assets/69723438/91a0704f-6304-4e38-8eea-910f2c73fb65)

**Comment by Amaya-2001** [comment]
> Doesn't handle decimal numbers, ![image](https://user-images.githubusercontent.com/69723438/250259637-91a0704f-6304-4e38-8eea-910f2c73fb65.png)
Thank You, now I fixed it.

**Comment by Amaya-2001** [comment]
fixed the decimal number handling issue
